name: CI/CD for Trivia Game

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.USERNAME }}"
          git config --global url.https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node packages
        run: yarn

      - name: Build and Deploy
        run: npm run deploy
